services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate --noinput &&
            python manage.py collectstatic --noinput &&
            python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=lecture_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: